/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/Onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/Perfil`; params?: Router.UnknownInputParams; } | { pathname: `/QrCodeScanner`; params?: Router.UnknownInputParams; } | { pathname: `/Receitas`; params?: Router.UnknownInputParams; } | { pathname: `/Register`; params?: Router.UnknownInputParams; } | { pathname: `/Reviews`; params?: Router.UnknownInputParams; } | { pathname: `/Reviews_Publicas`; params?: Router.UnknownInputParams; } | { pathname: `/Write_Review`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/Onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/Perfil`; params?: Router.UnknownOutputParams; } | { pathname: `/QrCodeScanner`; params?: Router.UnknownOutputParams; } | { pathname: `/Receitas`; params?: Router.UnknownOutputParams; } | { pathname: `/Register`; params?: Router.UnknownOutputParams; } | { pathname: `/Reviews`; params?: Router.UnknownOutputParams; } | { pathname: `/Reviews_Publicas`; params?: Router.UnknownOutputParams; } | { pathname: `/Write_Review`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/Login${`?${string}` | `#${string}` | ''}` | `/Onboarding${`?${string}` | `#${string}` | ''}` | `/Perfil${`?${string}` | `#${string}` | ''}` | `/QrCodeScanner${`?${string}` | `#${string}` | ''}` | `/Receitas${`?${string}` | `#${string}` | ''}` | `/Register${`?${string}` | `#${string}` | ''}` | `/Reviews${`?${string}` | `#${string}` | ''}` | `/Reviews_Publicas${`?${string}` | `#${string}` | ''}` | `/Write_Review${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/Onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/Perfil`; params?: Router.UnknownInputParams; } | { pathname: `/QrCodeScanner`; params?: Router.UnknownInputParams; } | { pathname: `/Receitas`; params?: Router.UnknownInputParams; } | { pathname: `/Register`; params?: Router.UnknownInputParams; } | { pathname: `/Reviews`; params?: Router.UnknownInputParams; } | { pathname: `/Reviews_Publicas`; params?: Router.UnknownInputParams; } | { pathname: `/Write_Review`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
